"""initial schema

Revision ID: 91711aab5efb
Revises: 
Create Date: 2026-03-15 22:17:17.340539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91711aab5efb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('train_id', sa.String(length=20), nullable=False),
    sa.Column('sensor_type', sa.Enum('VIBRATION', 'TEMPERATURE', 'DOOR_CYCLE', 'CURRENT_DRAW', name='sensortype'), nullable=False),
    sa.Column('detection_method', sa.String(length=30), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('line_id', sa.String(length=10), nullable=False),
    sa.Column('station_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_timestamp'), 'anomaly_events', ['timestamp'], unique=False)
    op.create_table('lta_disruptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('line_id', sa.String(length=10), nullable=False),
    sa.Column('station_id', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lta_disruptions_timestamp'), 'lta_disruptions', ['timestamp'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('train_id', sa.String(length=20), nullable=False),
    sa.Column('sensor_type', sa.Enum('VIBRATION', 'TEMPERATURE', 'DOOR_CYCLE', 'CURRENT_DRAW', name='sensortype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('line_id', sa.String(length=10), nullable=False),
    sa.Column('station_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_train_id'), 'sensor_readings', ['train_id'], unique=False)
    op.create_index('ix_sensor_readings_train_time', 'sensor_readings', ['train_id', 'timestamp'], unique=False)
    op.create_table('agent_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anomaly_event_id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('severity_override', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity'), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_event_id'], ['anomaly_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_assessments')
    op.drop_index('ix_sensor_readings_train_time', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_train_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_lta_disruptions_timestamp'), table_name='lta_disruptions')
    op.drop_table('lta_disruptions')
    op.drop_index(op.f('ix_anomaly_events_timestamp'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
